generator: generate code for more verbose serde_json errors
$ ./target/debug/varlink --activate './target/debug/ping --varlink $VARLINK_ADDRESS ' call org.example.ping.Ping '{ "pings" : "ping" }'
Error: Varlink Error: Invalid parameter: 'missing field `ping`'

instead of:

Error: Varlink Error: Connection Closed